# Generated by Django 4.1.5 on 2023-02-16 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('display_name', models.TextField()),
                ('icon', models.TextField()),
                ('guid', models.IntegerField()),
                ('can_be_hq', models.BooleanField(default=False)),
                ('stack_size', models.IntegerField()),
                ('jobs', models.TextField()),
                ('is_dyeable', models.BooleanField(default=False)),
                ('is_glamourous', models.BooleanField(default=False)),
                ('is_untradable', models.BooleanField(default=False)),
                ('is_marketable', models.BooleanField(default=False)),
                ('is_unique', models.BooleanField(default=False)),
                ('game_ui_category', models.TextField()),
                ('vendor_price', models.IntegerField()),
                ('game_search_category', models.TextField()),
                ('northamerica_listings_updated_at', models.DateTimeField(null=True)),
                ('northamerica_sales_updated_at', models.DateTimeField(null=True)),
                ('universalis_unresolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RunTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.TextField()),
                ('process_caller', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(null=True)),
                ('run_time', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='app.datacenter')),
            ],
        ),
        migrations.CreateModel(
            name='WorldItemFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nq_sold_mean', models.FloatField(null=True)),
                ('nq_sold_median', models.FloatField(null=True)),
                ('nq_sold_mode', models.FloatField(null=True)),
                ('nq_sold_high', models.IntegerField(null=True)),
                ('nq_sold_low', models.IntegerField(null=True)),
                ('nq_sold_count', models.IntegerField(null=True)),
                ('nq_sellers_count', models.IntegerField(null=True)),
                ('nq_list_mean', models.FloatField(null=True)),
                ('nq_list_median', models.FloatField(null=True)),
                ('nq_list_mode', models.FloatField(null=True)),
                ('nq_list_high', models.IntegerField(null=True)),
                ('nq_list_low', models.IntegerField(null=True)),
                ('nq_list_count', models.IntegerField(null=True)),
                ('hq_last_sold_value', models.IntegerField(null=True)),
                ('nq_last_sold_value', models.IntegerField(null=True)),
                ('hq_sold_mean', models.FloatField(null=True)),
                ('hq_sold_median', models.FloatField(null=True)),
                ('hq_sold_mode', models.FloatField(null=True)),
                ('hq_sold_high', models.IntegerField(null=True)),
                ('hq_sold_low', models.IntegerField(null=True)),
                ('hq_sold_count', models.IntegerField(null=True)),
                ('hq_sellers_count', models.IntegerField(null=True)),
                ('hq_list_mean', models.FloatField(null=True)),
                ('hq_list_median', models.FloatField(null=True)),
                ('hq_list_mode', models.FloatField(null=True)),
                ('hq_list_high', models.IntegerField(null=True)),
                ('hq_list_low', models.IntegerField(null=True)),
                ('hq_list_count', models.IntegerField(null=True)),
                ('calculated_at', models.DateTimeField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='app.item')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='app.world')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('buyer_name', models.TextField()),
                ('sold_at', models.DateTimeField()),
                ('hq', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app.item')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app.world')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon', models.TextField()),
                ('guid', models.IntegerField()),
                ('result_amount', models.IntegerField()),
                ('profession', models.TextField()),
                ('level', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='app.item')),
                ('materials', models.ManyToManyField(through='app.Ingredient', to='app.item')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_guid', models.TextField()),
                ('retainer_guid', models.TextField()),
                ('retainer_name', models.TextField()),
                ('price_per_unit', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('hq', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='app.item')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='app.world')),
            ],
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['guid'], name='app_item_guid_56b087_idx'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='app.item'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='app.recipe'),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_centers', to='app.region'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sold_at', 'buyer_name'], name='app_sale_sold_at_88a637_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['item_id'], name='app_sale_item_id_2cec9c_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sold_at'], name='app_sale_sold_at_62410f_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['guid'], name='app_recipe_guid_c69fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_guid'], name='app_listing_listing_e93d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['item_id'], name='app_listing_item_id_ac34ab_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['created_at'], name='app_listing_created_5f83fe_idx'),
        ),
    ]
