# Generated by Django 4.1.5 on 2023-01-30 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon', models.TextField()),
                ('guid', models.IntegerField()),
                ('northamerica_listings_updated_at', models.DateTimeField(null=True)),
                ('northamerica_sales_updated_at', models.DateTimeField(null=True)),
                ('universalis_unresolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('icon', models.TextField(null=True)),
                ('guid', models.IntegerField()),
                ('result_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('world', models.TextField()),
                ('price_per_unit', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('buyer_name', models.TextField()),
                ('sold_at', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app.item')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='app.RecipeItemIngredient', to='app.item'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item'),
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('world', models.TextField()),
                ('listing_guid', models.TextField()),
                ('retainer_guid', models.TextField()),
                ('retainer_name', models.TextField()),
                ('price_per_unit', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='app.item')),
            ],
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['guid'], name='app_item_guid_56b087_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sold_at', 'buyer_name'], name='app_sale_sold_at_88a637_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['guid'], name='app_recipe_guid_c69fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_guid'], name='app_listing_listing_e93d5f_idx'),
        ),
    ]
