# Generated by Django 4.1.5 on 2023-02-02 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='profession',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='app.item'),
        ),
    ]
