# Generated by Django 4.1.5 on 2023-02-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_dyeable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_glamourous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_untradable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='jobs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stack_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ui_category',
            field=models.TextField(null=True),
        ),
    ]
