# Generated by Django 4.1.5 on 2023-02-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sale_created_at_alter_listing_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='facts_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='listsings_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='market_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
