# Generated by Django 4.1.5 on 2023-02-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_is_dyeable_item_is_glamourous_item_is_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='vendor_price',
            field=models.IntegerField(null=True),
        ),
    ]
