# Generated by Django 4.1.5 on 2023-02-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_recipe_profession_alter_recipe_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='can_be_hq',
            field=models.BooleanField(default=True),
        ),
    ]
