# Generated by Django 4.1.5 on 2023-02-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_vendor_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='app.item'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='materials',
            field=models.ManyToManyField(related_name='xxx', through='app.Ingredient', to='app.item'),
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('data_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worlds', to='app.datacenter')),
            ],
        ),
        migrations.AddField(
            model_name='datacenter',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_centers', to='app.region'),
        ),
    ]
