# Generated by Django 4.1.5 on 2023-02-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_datacenter_region_alter_recipe_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='display_name',
            field=models.TextField(null=True),
        ),
    ]
