# Generated by Django 4.2.1 on 2023-06-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_listing_datacenter_sale_datacenter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
