# Generated by Django 4.1.5 on 2023-02-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldItemFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_mean', models.FloatField()),
                ('sold_median', models.FloatField()),
                ('sold_avg', models.FloatField()),
                ('sold_high', models.IntegerField()),
                ('sold_low', models.IntegerField()),
                ('sold_count', models.IntegerField()),
                ('sellers_count', models.IntegerField()),
                ('list_mean', models.FloatField()),
                ('list_median', models.FloatField()),
                ('list_avg', models.FloatField()),
                ('list_high', models.IntegerField()),
                ('list_low', models.IntegerField()),
                ('list_count', models.IntegerField()),
                ('hq', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='hq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='hq',
            field=models.BooleanField(default=False),
        ),
    ]
