# Generated by Django 4.2.1 on 2023-06-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item_equip_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='level',
            new_name='item_level',
        ),
    ]
