# Generated by Django 4.2.1 on 2023-06-20 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bestcraftpricing_bestpurchasepricing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worlditemfact',
            name='hq_list_high',
        ),
        migrations.RemoveField(
            model_name='worlditemfact',
            name='hq_list_median',
        ),
        migrations.RemoveField(
            model_name='worlditemfact',
            name='hq_list_mode',
        ),
        migrations.AlterField(
            model_name='bestpurchasepricing',
            name='best_hq_listing_in_datacenter_world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.world'),
        ),
        migrations.AlterField(
            model_name='bestpurchasepricing',
            name='best_hq_listing_in_region_world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.world'),
        ),
        migrations.AlterField(
            model_name='bestpurchasepricing',
            name='best_nq_listing_in_datacenter_world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.world'),
        ),
        migrations.AlterField(
            model_name='bestpurchasepricing',
            name='best_nq_listing_in_region_world',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.world'),
        ),
        migrations.AlterField(
            model_name='worlditemfact',
            name='hq_list_mean',
            field=models.IntegerField(null=True),
        ),
    ]
