# Generated by Django 4.2.1 on 2023-06-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_worlditemfact_hq_list_high_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bestpurchasepricing',
            index=models.Index(fields=['item_id'], name='app_bestpur_item_id_74f9a4_idx'),
        ),
        migrations.AddIndex(
            model_name='bestpurchasepricing',
            index=models.Index(fields=['home_id'], name='app_bestpur_home_id_10ebfc_idx'),
        ),
    ]
