# Generated by Django 4.2.1 on 2023-06-30 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_bestpurchasepricing_app_bestpur_item_id_74f9a4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bestcraftpricing',
            name='datacenter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.datacenter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='home',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.world'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='hq_dc_craft_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='hq_dc_craft_price_is_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='hq_home_craft_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='hq_home_craft_price_is_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='hq_region_craft_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='hq_region_craft_price_is_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='nq_dc_craft_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='nq_dc_craft_price_is_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='nq_home_craft_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='nq_home_craft_price_is_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='nq_region_craft_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='nq_region_craft_price_is_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bestcraftpricing',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.region'),
            preserve_default=False,
        ),
    ]
