# Generated by Django 4.2.1 on 2023-06-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_bestcraftpricing_datacenter_bestcraftpricing_home_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestcraftpricing',
            name='hq_dc_craft_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bestcraftpricing',
            name='hq_home_craft_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bestcraftpricing',
            name='hq_region_craft_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bestcraftpricing',
            name='nq_dc_craft_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bestcraftpricing',
            name='nq_home_craft_price',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bestcraftpricing',
            name='nq_region_craft_price',
            field=models.BigIntegerField(null=True),
        ),
    ]
