# Generated by Django 4.2.1 on 2023-07-30 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_bestcraftpricing_hq_dc_craft_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CraftList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.TextField()),
                ('home_price', models.IntegerField()),
                ('home_price_partial', models.BooleanField(default=False)),
                ('dc_price', models.IntegerField()),
                ('dc_price_partial', models.BooleanField(default=False)),
                ('reg_price', models.IntegerField()),
                ('reg_price_partial', models.BooleanField(default=False)),
                ('dc_shopping_list', models.TextField()),
                ('reg_shopping_list', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.world')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recipe')),
            ],
        ),
    ]
