# Generated by Django 4.2.1 on 2023-08-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_craftlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftlist',
            name='dc_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='craftlist',
            name='home_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='craftlist',
            name='reg_price',
            field=models.BigIntegerField(),
        ),
    ]
