# Generated by Django 4.2.1 on 2023-08-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_craftlist_dc_price_alter_craftlist_home_price_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='world',
            index=models.Index(fields=['name'], name='app_world_name_bc7589_idx'),
        ),
        migrations.AddIndex(
            model_name='worlditemfact',
            index=models.Index(fields=['item_id', 'world_id'], name='app_worldit_item_id_32956f_idx'),
        ),
    ]
